<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>

<?php $buttonTitle = __('Add to Cart'); ?>
<?php $buttonTitleEnable = __('Enable Enquiry'); ?>


<?php if ($_product->isSaleable()) :?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       min="0"
                       value="<?= $block->getProductDefaultQty() * 1 ?>"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
        </div>
        <?php endif; ?>
        <?php if($_product->getAttributeText('hide_add_to_cart') == "No") {?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button" disabled>
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
        <?php }else{?>           
            <span class="enable_enquiry_cart open-modal-form">Enable Enquiry</span>
        <?php }?>
    </div>
</div>
<?php endif; ?>

            <div style="display: none;" id="modal-form">
                <div>
                <form>
                    <input type="text" name="name" value="" hidden>
                </form>
                <form action="<?=$block->getUrl('attribute/index/save')?>" method="POST" id="enquiry-form-validation" data-hasrequired="<?php echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
                    <fieldset class="fieldset">
                        <div class="field prd_url required">
                            <label class="label" for="prd_url"><span><?= $block->escapeHtml(__('Product Url')) ?></span></label>
                            <div class="control">
                                <input type="text" id="prd_url" name="prd_url" value="<?= $_product->getProductUrl() ?>">
                            </div>
                        </div>
                        <div class="field prd_name required">
                            <label class="label" for="prd_name"><span><?= $block->escapeHtml(__('Product Name')) ?></span></label>
                            <div class="control">
                                <input type="text" id="prd_name" name="product_name" value="<?= $_product->getName() ?>">
                            </div>
                        </div>
                        <div class="field customer_name required">
                            <label class="label" for="customer_name"><span><?= $block->escapeHtml(__('Customer Name')) ?></span></label>
                            <div class="control">
                                <input type="text" name="customer_name" data-validate="{required:true}" >
                            </div>
                        </div>
                        <div class="field email required">
                            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                            <div class="control">
                                
                                <input type="email" name="email" data-validate="{required:true, 'validate-email':true}">
                            </div>
                        </div>
                        <div class="field comment required">
                            <label class="label" for="comment"><span><?= $block->escapeHtml(__('Comment')) ?></span></label>
                            <div class="control">
                                <input type="text" name="comment" data-validate="{required:true}" >
                            </div>
                        </div>
                    </fieldset>
                    <input type="submit" name="popup_submit" value="Submit your form" class="enable_enquiry">
                </form>
            </div>
        </div>

<script type="text/x-magento-init">
    {
        ".open-modal-form": {
            "Product_Attribute/js/modal-form": {}
        }
    }
</script>

<script type="text/x-magento-init">
    {
        "#enquiry-form-validation": {
            "validation": {}
        }
    }
</script>

<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
