<?php
    $collection = $block->getEditData();
    //echo "Hello";
    //print_r($collection);


    //die();
?>


<form method="POST" action="<?php echo $this->getUrl('helloworld/index/save', ['_secure' => true]);?>"> 
    <fieldset class="fieldset">
        <input type="hidden" name="post_id" id="post_id" value="<?= $collection['post_id']; ?>" />
        <br>
        <div class="field id required">
            <label class="form-label" for="name">Post Name</label>
            <div class="control">
                <input type="text" class="input-text" id="name" name="name" value="<?= $collection['name']; ?>" />
            </div>
        </div>
        <div class="field id required">
            <label class="form-label" for="url_key">Post URL Key</label>
            <div class="control">
                <input type="text" class="input-text" id="url_key" name="url_key" value="<?= $collection['url_key']; ?>" />
            </div>
        </div>

        <div class="field id required">
            <label class="form-label" for="post_content">Post Post Content</label>
            <div class="control">
                <input type="text" class="input-text" id="post_content" name="post_content" value="<?= $collection['post_content']; ?>" />
            </div>
        </div>

        <div class="field id required">
            <label class="form-label" for="tags">Post Tags</label>
            <div class="control">
                <input type="text" class="input-text" id="tags" name="tags" value="<?= $collection['tags']; ?>" />
            </div>
        </div>
        <div class="field id required">
            <label class="form-label" for="status">Post Status</label>
            <div class="control">
                <input type="text" class="input-text" id="status" name="status" value="<?= $collection['status']; ?>" />
            </div>
        </div>
        <div class="field id required">
            <label class="form-label" for="featured_image">Post Featured Image</label>
            <div class="control">
                <input type="text" class="input-text" id="featured_image" name="featured_image" value="<?= $collection['featured_image']; ?>" />
            </div>
        </div>


        
    <div class="actions-toolbar">
        <div class="primary">
            <button id="submit" type="submit" title="submit">Submit
            </button>
        </div>
    </div>
</form>
