<?php
$object_manager = \Magento\Framework\App\ObjectManager::getInstance();
$productCollection = $object_manager->create('Chilliapple\Log\Model\ResourceModel\Log\Collection');
$collection = $productCollection->addFieldToSelect('*')
    ->addFieldToFilter('id', $this->getRequest()->getParam('id'))->load();

foreach ($collection as $log) {
?>
    <div class="card">
        <a class="btn" href="<?php echo $block->getUrl('log/log/index') ?>"><?php echo __('Go Back') ?></a>
        
        <h1><?php echo $log->log() . '   ' . $log->comment(); ?></h1>
        <p><button>Contact</button></p>
    </div>
<?php
}
?>
